### PR TITLE
Removing String's deprecated APIs and modifying for Swift 4

### PR DESCRIPTION
**Pull request by avinashdongarwar**
Removed use of `substring(from)` api and updated for new syntax.

### CODE REVIEW

**Comment by kylef** [comment]
This would break Swift 3 compatibility wouldn't it?

**Comment by keith** [comment]
This doesn't break 3.2 compatibility, because this was valid and just warned for that version. I think that Xcode 8 support is already broken since the Package.swift is in tools version 4.

@avinashdongarwar can you rebase here?

**Comment by keith** [comment]
You can see this still works with:

```
swift build -Xswiftc -swift-version -Xswiftc 3
```

**Comment by keith** [comment]
Thanks for submitting this, this has been fixed as part of https://github.com/kylef/PathKit/pull/48 and release as 0.9.1

**Pull request closed without merging**
